require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.bufferline")
require("core.plugin_config.terminal")
require("core.plugin_config.dashboard")
require("core.plugin_config.lsp")
--require("scope").setup({})
--require("telescope").load_extension("scope")
require("cybu").setup({})
require('vgit').setup({})
--require('qf').setup({})

